- hosts: all
  tasks:
  - name: override sources.list
    copy:
      src: sources.list
      dest: /etc/apt/sources.list

  - name: Add an Apt signing key to a specific keyring file
    apt_key:
      file: ./apt-key.gpg
      keyring: /usr/share/keyrings/kubernetes-archive-keyring.gpg

  - name: update apt
    apt:
      update_cache: yes

  - name: Disable SWAP since kubernetes can't work with swap enabled
    shell: |
      swapoff -a


 


  - name: install kubelet
    apt:
      name: 
        - kubelet=1.23.17-00
      state: present

  - name: install kubeadm
    apt:
      name: 
        - kubeadm=1.23.17-00
      state: present

  - name: install kubectl
    apt:
      name: kubectl
      state: latest

  - name: install docker
    apt:
      name: docker.io
      state: latest

  - name: install docker
    shell: |
        echo '{"exec-opts": ["native.cgroupdriver=systemd"]}' > /etc/docker/daemon.json

  - name: Restart docker
    systemd:
      name: docker  
      state: restarted

 

  - name: pull k8s images
    script: ./install_docker.sh

 